steps:
  - name: "docker"
    id: "docker"
    entrypoint: "docker"
    args: [
      "build",
      "-f", "Dockerfile",
      "-t", "gcr.io/$PROJECT_ID/celostats-frontend:$BRANCH_NAME",
      "."
    ]
    waitFor: ["-"]
timeout: 1200s
images:
  - "gcr.io/$PROJECT_ID/celostats-frontend:$BRANCH_NAME"
