version: 2

workflows:
  version: 2
  CI:
    jobs:
      - npm-install
      - test:
          requires:
            - npm-install
      # - test-e2e:
      #     requires:
      #       - npm-install
      - lint:
          requires:
            - npm-install
      - build-app:
          requires:
            - npm-install

node-defaults: &NODE
  working_directory: ~/workspace
  docker:
    - image: circleci/node:10.18-browsers

checkout-workspace-defaults:
  - &CHECKOUT-WORKSPACE
    attach_workspace:
      at: ~/workspace

jobs:
  # NPM install
  npm-install:
    <<: *NODE
    steps:
      - checkout
      - *CHECKOUT-WORKSPACE
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  # Tests
  test:
    <<: *NODE
    steps:
      - checkout
      - *CHECKOUT-WORKSPACE
      - run: npm run test
      - store_test_results:
          path: coverage/junit
      - store_artifacts:
          path: coverage
      - persist_to_workspace:
          root: .
          paths:
            - coverage
  # Code quality
  lint:
    <<: *NODE
    steps:
      - checkout
      - *CHECKOUT-WORKSPACE
      - run: npm run lint
  # Build
  build-app:
    <<: *NODE
    steps:
      - checkout
      - *CHECKOUT-WORKSPACE
      - run: npm run build -- --base-href "./"
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
