version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6

workflows:
  version: 2
  CI:
    jobs:
      - npm-install
      - test:
          requires:
            - npm-install
      # - test-e2e:
      #     requires:
      #       - npm-install
      - lint:
          requires:
            - npm-install
      - build-app:
          requires:
            - npm-install

node-defaults: &NODE
  working_directory: ~/workspace
  docker:
    - image: cimg/node:lts-browsers

checkout-workspace-defaults:
  - &CHECKOUT-WORKSPACE
    attach_workspace:
      at: ~/workspace

jobs:
  # NPM install
  npm-install:
    <<: *NODE
    steps:
      - checkout
      - *CHECKOUT-WORKSPACE
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: 
          command: |
            yarn
          environment:
            NODE_ENV: --openssl-legacy-provider
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  # Tests
  test:
    <<: *NODE
    steps:
      - checkout
      - *CHECKOUT-WORKSPACE
      - run: 
          command: |
            yarn test
          environment:
            NODE_ENV: --openssl-legacy-provider
      - store_test_results:
          path: coverage/junit
      - store_artifacts:
          path: coverage
      - persist_to_workspace:
          root: .
          paths:
            - coverage
  # Code quality
  lint:
    <<: *NODE
    steps:
      - checkout
      - *CHECKOUT-WORKSPACE
      - run: 
          command: |
            yarn lint
          environment:
            NODE_ENV: --openssl-legacy-provider
  # Build
  build-app:
    <<: *NODE
    steps:
      - checkout
      - *CHECKOUT-WORKSPACE
      - run: 
          command: yarn build -- --base-href "./"
          environment:
            NODE_ENV: --openssl-legacy-provider
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
