---
  name: Build containers for celostats-frontend
      
  on:
    push:
      branches:
        - "master"
    release:
      types: [published]
    pull_request:
      branches:
        - "master"
    workflow_dispatch:
      
      
  jobs:
    celostats-frontend-build-dev:
      uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v2.0.4
      name: Build us-west1-docker.pkg.dev/devopsre/dev-images/celostats-frontend
      permissions:
        contents: read
        id-token: write
        security-events: write
      if: ${{ github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/pull/') }}
      with:
        workload-id-provider: 'projects/1094498259535/locations/global/workloadIdentityPools/gh-celostats-frontend/providers/github-by-repos'
        service-account: 'celostats-frontend-dev@devopsre.iam.gserviceaccount.com'
        artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/celostats-frontend
        tags: test
        context: .
        file: ./Dockerfile
        trivy: true
  
    celostats-frontend-build-main:
      uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v2.0.4
      name: Build us-west1-docker.pkg.dev/devopsre/celostats-frontend/celostats-frontend
      permissions:
        contents: read
        id-token: write
        security-events: write
      if: |
        github.ref == 'refs/heads/master'
      with:
        workload-id-provider: 'projects/1094498259535/locations/global/workloadIdentityPools/gh-celostats-frontend-master/providers/github-by-repos'
        service-account: 'celostats-frontend@devopsre.iam.gserviceaccount.com'
        artifact-registry: us-west1-docker.pkg.dev/devopsre/celostats-frontend/celostats-frontend
        tags: latest
        context: .
        file: ./Dockerfile
        trivy: true
  
    celostats-frontend-build-tag:
      uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v2.0.4
      name: Build us-west1-docker.pkg.dev/devopsre/celostats-frontend/celostats-frontend tag
      permissions:
        contents: read
        id-token: write
        security-events: write
      if: |
        startsWith(github.ref, 'refs/tags/')
      with:
        workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celostats-frontend-master/providers/github-by-repos
        service-account: 'celostats-frontend@devopsre.iam.gserviceaccount.com'
        artifact-registry: us-west1-docker.pkg.dev/devopsre/celostats-frontend/celostats-frontend
        tags: ${{ github.ref_name }}
        context: .
        file: ./Dockerfile
        trivy: true
